language: python

python:
    - "3.4"
    - "3.5"

sudo: false

install:
    - "pip install -r requirements.txt"

script: py.test --cov=abbot --cov=holy_orders
after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: always
