---
- name: check whether NodeJS is downloaded
  stat: path={{ nodejs_local_path }}
  register: nodejs_is_downloaded

- name: download the source file
  when: not nodejs_is_downloaded.stat.exists
  get_url: url={{ nodejs_download_url }} dest={{ nodejs_local_path }}

- name: extract program code
  unarchive: copy=no src={{ nodejs_local_path }} dest=/usr/local

- name: remove downloaded NodeJS file
  file: path={{ nodejs_local_path }} state=absent
