---
- name: see whether NodeJS {{ nodejs_version }} is already installed
  stat: path={{ nodejs_bin_dir }}
  register: nodejs_is_installed

- include: install_nodejs.yml
  when: not nodejs_is_installed.stat.exists

- name: set permissions on installed program code
  file:
    path: "{{ nodejs_bin_dir }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwX,g=rX,o=rX"
    recurse: yes
    setype: usr_t
    seuser: system_u

- name: set permissions on the "node" and "npm" executables
  file:
    path: "{{ item }}"
    state: file
    mode: "u=rwx,g=rx,o=rx"
  with_items:
    - "{{ nodejs_executable }}"
    - "{{ npm_executable }}"

- name: make symlinks to executables
  file: state=link src={{ item.src }} dest={{ item.dest }}
  with_items:
    - "{'src': '{{ nodejs_executable }}', 'dest': '/usr/bin/node'}"
    - "{'src': '{{ npm_executable }}', 'dest': '/usr/bin/npm'}"
