---
- name: (local) check for dependencies
  connection: local
  become: false
  command: which {{ item }}
  with_items:
    - node
    - npm
    - git

- name: (local) clone the Vitrail repository
  connection: local
  become: false
  git:
    dest: "{{ vitrail_repo_local }}"
    force: yes
    repo: "{{ vitrail_repo }}"
    version: "{{ vitrail_version }}"

- name: (local) set the Abbot server URL for Vitrail
  connection: local
  become: false
  lineinfile:
    state: present
    dest: "{{ item }}"
    regexp: '<< SERVER URL HERE >>'
    line: "{{ abbot_url_for_vitrail }}"
  with_items:
    - "{{ vitrail_repo_local }}/js/nuclear/signals.js"
    - "{{ vitrail_repo_local }}/serviceworker.js"

# the Ansible "npm" module doesn't seem to update dependencies
- name: (local) install NPM depenencies
  connection: local
  become: false
  command: "npm install chdir={{ vitrail_repo_local }}"

- name: (local) build a Vitrail deployment bundle
  connection: local
  become: false
  command: "python3 build_deploy_bundle.py chdir={{ vitrail_repo_local }}"

- name: delete remote {{ vitrail_document_root }}
  file: dest={{ vitrail_document_root }} state=absent
- name: create remote {{ vitrail_document_root }}
  file:
    dest: "{{ vitrail_document_root }}"
    state: directory

- name: copy and unarchive the deployment bundle "{{ vitrail_repo_local }}/deploy.xz"
  unarchive:
    copy: yes
    src: "{{ vitrail_repo_local }}/deploy.xz"
    dest: "{{ vitrail_document_root }}"
    owner: root
    group: root
    mode: "u=rwX,g=rX,o=rX"
    setype: httpd_sys_content_t

- name: double-check that httpd is started
  service: name=httpd state=started
