---
vitrail_repo: https://github.com/CANTUS-Project/vitrail.git
vitrail_repo_local: vitrail
# this is set in group_vars so HTTPD config can access it too
# vitrail_document_root = /var/www/vitrail (or whatever
