---
- name: generate the Abbot configuration file
  template:
    src: config.ini.j2
    dest: "{{ holyorders_conf_file }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    seuser: system_u
    setype: etc_t
  notify:
    - restart holyorders

# NB: the configuration file MUST be written before the database is created
- name: create the directory for the updates database
  file:
    path: "{{ holyorders_updates_db_dir }}"
    owner: "{{ abbot_user }}"
    group: "{{ abbot_group }}"
    mode: "u=rwX,g=rX,o=rX"
    seuser: system_u
    setype: var_t
    state: directory
- name: create the updates database (if required)
  command: "python3 {{ holyorders_make_db }} {{ holyorders_conf_file }}"
  args:
    creates: "{{ holyorders_updates_db }}"
- name: check permissions on the updates database
  file:
    path: "{{ holyorders_updates_db }}"
    owner: "{{ abbot_user }}"
    group: "{{ abbot_group }}"
    mode: "u=rw,g=r,o=r"
    seuser: system_u
    setype: var_t
    state: file

- name: install systemd unit file for HolyOrders
  template:
    src: holyorders.service.j2
    dest: "{{ unit_files_dir }}/holyorders.service"
    owner: root
    group: root
    seuser: system_u
    setype: systemd_unit_file_t
  notify:
    - daemon-reload
    - restart holyorders
- name: install systemd timer file for HolyOrders
  template:
    src: holyorders.timer.j2
    dest: "{{ unit_files_dir }}/holyorders.timer"
    owner: root
    group: root
    seuser: system_u
    setype: systemd_unit_file_t
  notify:
    - daemon-reload
    - restart holyorders

- name: enable HolyOrders
  service: name=holyorders.timer enabled=yes
