---
- name: install Java 1.8
  yum: name={{ item }} state=present
  with_items: [ 'java-1.8.0-openjdk', 'java-1.8.0-openjdk-devel', 'java-1.8.0-openjdk-headless' ]

- name: remove Java 1.7
  yum: name={{ item }} state=absent
  with_items: [ 'java-1.7.0-openjdk', 'java-1.7.0-openjdk-devel', 'java-1.7.0-openjdk-headless' ]
