#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#--------------------------------------------------------------------------------------------------
# Program Name:           abbott
# Program Description:    HTTP Server for the CANTUS Database
#
# Filename:               scripts/start_abbott
# Purpose:                Starts Abbott in the current proces (for deployment).
#
# Copyright (C) 2015 Christopher Antila
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#--------------------------------------------------------------------------------------------------
'''
Starts Abbott in the current process.

This script is to be used for deployment. Commandline arguments given to this script will be read
into Abbott's configuration.
'''


import os
import os.path
import sys


# Configuration Variables
# -----------------------
# NOTE: you must customize these variables for every deployment

# path to the virtualenv directory
VENV_PATH = '/usr/local/abbott-venv'

# path to the Abbott code
ABBOTT_PATH = '/usr/local/abbott'

# Script
# ------
# NOTE: don't customize this part

def activate_this():
    '''
    This function was taken almost verbatim from the Python2 "virtualenv" package's
    "activate_this.py" script.
    '''
    old_os_path = os.environ['PATH']
    os.environ['PATH'] = VENV_PATH + os.pathsep + old_os_path
    site_packages = [VENV_PATH, 'lib',
                     'python{}.{}'.format(sys.version_info.major, sys.version_info.minor),
                     'site-packages']
    site_packages = os.path.join(*site_packages)
    prev_sys_path = list(sys.path)
    import site
    site.addsitedir(site_packages)
    sys.real_prefix = sys.prefix
    sys.prefix = VENV_PATH
    # Move the added items to the front of the path:
    new_sys_path = []
    for item in list(sys.path):
        if item not in prev_sys_path:
            new_sys_path.append(item)
            sys.path.remove(item)
    sys.path[:0] = new_sys_path

ABBOTT_MAIN = '{}/abbott/__main__.py'.format(ABBOTT_PATH)
with open(ABBOTT_MAIN) as abbott_file:
    COMPILED = compile(abbott_file.read(), ABBOTT_MAIN, 'exec')

exec(COMPILED, globals(), locals())  # pylint: disable=exec-used
