#!/usr/bin/env python
# -*- coding: utf-8 -*-
#--------------------------------------------------------------------------------------------------
# Program Name:           abbot
# Program Description:    HTTP Server for the CANTUS Database
#
# Filename:               scripts/start_abbot
# Purpose:                Starts Abbot in a new process (for deployment without systemd).
#
# Copyright (C) 2015 Christopher Antila
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#--------------------------------------------------------------------------------------------------
'''
Starts Abbot in a new process (for deployment without systemd).

Please note that this is not the recommended deployment mechanism. We recommend a production server
with a Linux-based OS that uses systemd, which allows using the "abbot.service" and "abbot.socket"
files stored in this directory.

Unlike the rest of Abbot, this script works with both Python 2 and Python 3.
'''

import os
import os.path
import subprocess
import sys


# Configuration Variables
# -----------------------
# NOTE: you must customize these variables for every deployment

# path to the virtualenv directory
VENV_PATH = '/usr/local/abbot-venv'

# path to the Abbot code
Abbot_PATH = '/usr/local/abbot'

# path to the "PID file" that records the started server's process ID
PID_PATH = '/run/abbot/abbot.pid'

# Script
# ------
# NOTE: don't customize this part
os.environ['PYTHONPATH'] = Abbot_PATH
python = os.path.join(VENV_PATH, 'bin/python')
main_file = os.path.join(Abbot_PATH, 'abbot/__main__.py')
commandline = [python, main_file]

# append all the commandline arguments to this script into the next
for each_arg in sys.argv[1:]:
    commandline.append(each_arg)

abbot = subprocess.Popen(commandline, stdout=None, stderr=None)
try:
    with open(PID_PATH, 'w') as pid_file:
        pid_file.write(str(abbot.pid))
except IOError:
    # probably couldn't write to the PID_PATH
    print('Could not write PID file. Aborting startup.')
    abbot.kill()
    raise SystemExit(1)
