---
- include: install_py3.yml

- hosts: abbot
  name: install Abbot
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    abbot_version: master
    abbot_repo: https://github.com/CANTUS-Project/abbot.git
    abbot_bin_dir: /usr/local/abbot
    abbot_venv_dir: /usr/local/abbot-venv
    abbot_py_exec: "{{ abbot_venv_dir }}/bin/python"
    abbot_user: abbot
    abbot_group: "{{ abbot_user }}"
    abbot_conf_file: /etc/abbot.conf
    unit_files_dir: /usr/lib/systemd/system
    # for the configuration file
    abbot_port: 8888
    abbot_scheme: http
    abbot_hostname: abbot.adjectivenoun.ca
    abbot_cors_origin: "*"
    abbot_drupal_url: http://cantus.uwaterloo.ca/
    abbot_solr_url: http://localhost:8983/solr/collection1/

  tasks:
    # download Abbot repository and checkout the proper commit
    - name: check that git is installed
      yum: name=git state=present
    - name: clone the "abbot" repository
      git:
        clone: yes
        update: yes
        force: yes  # meaning to overwrite local changes
        dest: "{{ abbot_bin_dir }}"
        repo: "{{ abbot_repo }}"
        version: "{{ abbot_version }}"
      notify:
        - restart abbot
    - name: set permissions on the abbot directory
      file:
        path: "{{ abbot_bin_dir }}"
        state: directory
        owner: root
        group: root
        mode: "u=rwX,g=rX,o=rX"
        seuser: system_u
        setype: usr_t
    - name: set SELinux type on the abbot Python files
      file: path={{ item }} state=directory recurse=yes setype=usr_t
      with_items:
        - "{{ abbot_bin_dir }}/packaging"
        - "{{ abbot_bin_dir }}/scripts"
        - "{{ abbot_bin_dir }}/tests"
        - "{{ abbot_bin_dir }}/test_client"
    - name: set SELinux type on the abbot Python lib files
      file: path={{ abbot_bin_dir }}/abbot state=directory setype=lib_t

    # setup the virtualenv
    - name: check whether the virtualenv exists
      stat: path={{ abbot_venv_dir }}/bin/python
      register: venv_exists
    - name: make the virtualenv
      when: not venv_exists.stat.exists
      shell: /usr/bin/pyvenv-3.4 {{ abbot_venv_dir }}
    - name: install/update all requirements with pip
      pip:
        virtualenv: "{{ abbot_venv_dir }}"
        requirements: "{{ abbot_bin_dir }}/requirements-deploy.txt"
      notify:
        - restart abbot
    - name: install abbot to the virtualenv
      pip: virtualenv={{ abbot_venv_dir }} name={{ abbot_bin_dir }}
    - name: set permissions on the virtualenv
      file:
        path: "{{ abbot_venv_dir }}"
        state: directory
        owner: root
        group: root
        mode: "u=rwX,g=rX,o=rX"
        seuser: system_u
        setype: usr_t
    - name: set permissions on the virtualenv/lib
      file:
        path: "{{ abbot_venv_dir }}/lib"
        state: directory
        owner: root
        group: root
        mode: "u=rwX,g=rX,o=rX"
        recurse: yes
        seuser: system_u
        setype: lib_t
    - name: set permissions on the virtualenv/bin
      file:
        path: "{{ abbot_venv_dir }}/bin"
        state: directory
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"
        recurse: yes
        seuser: system_u
        setype: bin_t

    # make the Abbot configuration
    - name: make the "abbot" user
      user: name={{ abbot_user }} state=present system=yes shell=/usr/sbin/nologin createhome=no
    - name: generate the Abbot configuration file
      template:
        src: abbot_config.py.j2
        dest: "{{ abbot_conf_file }}"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
        seuser: system_u
        setype: etc_t
      notify:
        - restart abbot
    - name: install systemd unit file for Abbot
      template:
        src: abbot.service.j2
        dest: "{{ unit_files_dir }}/abbot.service"
        owner: root
        group: root
        seuser: system_u
        setype: systemd_unit_file_t
      notify:
        - daemon-reload
        - restart abbot
    - name: install systemd socket file for Abbot
      template:
        src: abbot.socket.j2
        dest: "{{ unit_files_dir }}/abbot.socket"
        owner: root
        group: root
        seuser: system_u
        setype: systemd_unit_file_t
      notify:
        - daemon-reload
        - restart abbot
    - name: open Abbot's port in the firewall (permanent)
      firewalld: permanent=yes port={{ abbot_port }}/tcp state=enabled zone=public
    - name: open Abbot's port in the firewall (now)
      firewalld: permanent=no port={{ abbot_port }}/tcp state=enabled zone=public

  handlers:
    - name: daemon-reload
      shell: systemctl daemon-reload
    - name: restart abbot
      service: name=abbot state=restarted
