---
- include: epel_repo.yml

- hosts: abbot
  name: install IUS Community repository
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    ius_key_path: /etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY
    ius_rpm_path: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm
    ius_repo_path: /etc/yum.repos.d/ius.repo

  tasks:
    - name: check whether IUS is installed
      stat: path={{ ius_repo_path }}
      register: ius_stat
    - name: install IUS
      when: not ius_stat.stat.exists
      yum: name={{ ius_rpm_path }} state=present
    - name: install IUS GPG key
      rpm_key: state=present key={{ ius_key_path }}
    - name: ensure IUS is at latest version
      yum: name=ius-release state=latest
