---
- name: install letsencrypt
  package: name=letsencrypt state=present

- name: shut down httpd
  service: name=httpd state=stopped

- name: renew the certificate if relevant
  command: "letsencrypt certonly --standalone --standalone-supported-challenges http-01 --agree-tos --no-self-upgrade --rsa-key-size {{ rsa_key_size }} --keep-until-expiring -d {{ hostname }}"

- name: start httpd
  service: name=httpd state=started

- name: check permissions on letsencrypt directory
  file:
    path: /etc/letsencrypt
    follow: no
    owner: root
    group: abbot
    mode: u=rwX,g=rX,o=
    setype: etc_t
    state: directory
    recurse: yes
