---
- name: install certbot
  package: name=certbot state=present

- name: shut down httpd
  service: name=httpd state=stopped

- name: renew the certificate if relevant
  command: "certbot certonly --quiet --agree-tos --standalone --rsa-key-size {{ rsa_key_size }} --keep-until-expiring -d {{ hostname }}"

- name: check permissions on letsencrypt directory
  file:
    path: /etc/letsencrypt
    follow: no
    owner: root
    group: abbot
    mode: u=rwX,g=rX,o=
    setype: etc_t
    state: directory
    recurse: yes
